# Wana OS Android compatibility container.
lxc.rootfs.path = dir:/var/lib/wana/android/rootfs
lxc.arch = x86_64
lxc.autodev = 1
lxc.pty.max = 1024
lxc.mount.auto = proc:mixed sys:ro cgroup:mixed
lxc.net.0.type = none
lxc.cap.drop =
lxc.apparmor.profile = unconfined
lxc.mount.entry = /dev/binder dev/binder none bind,create=file,optional 0 0
lxc.mount.entry = /dev/hwbinder dev/hwbinder none bind,create=file,optional 0 0
lxc.mount.entry = /dev/vndbinder dev/vndbinder none bind,create=file,optional 0 0
lxc.mount.entry = /dev/dri dev/dri none rbind,create=dir,optional 0 0
lxc.mount.entry = /dev/input dev/input none rbind,create=dir,optional 0 0
lxc.mount.entry = /run/user/1000 run/user/1000 none rbind,create=dir,optional 0 0
lxc.environment = XDG_RUNTIME_DIR=/run/user/1000
