[package]
name = "wana-update-ui"
description = "Wana OS native system update UI"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
wana-client = { path = "../wana-client" }
wana-log = { path = "../wana-log" }
wana-text = { path = "../wana-text" }
wana-theme = { path = "../wana-theme" }

[lints]
workspace = true
