[package]
name = "wana-compositor"
description = "Wana OS compositor"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
wana-log = { path = "../wana-log" }
wana-wayland = { path = "../wana-wayland" }
wana-drm = { path = "../wana-drm" }

[lints]
workspace = true
